// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetWines():Promise<Array<main.Wine>>;

export function ImportFileFromJstoGo(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;
