// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function AddWine(arg1:string):Promise<any>;

export function DeleteWines(arg1:Array<string>):Promise<void>;

export function GetAllWineries():Promise<Array<services.Winery>>;

export function GetWines():Promise<Array<services.Wine>>;

export function ImportFileFromJstoGo(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;
