// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWine(arg1) {
  return window['go']['main']['App']['AddWine'](arg1);
}

export function AddWinery(arg1) {
  return window['go']['main']['App']['AddWinery'](arg1);
}

export function DeleteWines(arg1) {
  return window['go']['main']['App']['DeleteWines'](arg1);
}

export function GetAllWineries() {
  return window['go']['main']['App']['GetAllWineries']();
}

export function GetWines() {
  return window['go']['main']['App']['GetWines']();
}

export function ImportFileFromJstoGo(arg1) {
  return window['go']['main']['App']['ImportFileFromJstoGo'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}
